### PR TITLE
Add tabs position configuration

### PR DESCRIPTION
**Pull request by slavamuravey**
Hello! This PR adds the tabs positioning feature. Please, consider it.

### CODE REVIEW

**Comment by rinick** [comment]
Hi, this looks very promising.
But right now I don't really have much time to review and test it.
Could you also add an example page for tabPosition so I will be able to do some test quickly

**Comment by rinick** [comment]
@slavamuravey your latest update broke all the examples
so you want to completely broke all the backward compatibility?

**Comment by rinick** [comment]
Just tested this, even with only the first commit, there are still many things to fix, especially the css for left and right tab bars. 

I will close it for now, if you still need to merge the tab position change, please make a clean PR that doesn't break examples

**Comment by slavamuravey** [comment]
> Just tested this, even with only the first commit, there are still many things to fix, especially the css for left and right tab bars.
> 
> I will close it for now, if you still need to merge the tab position change, please make a clean PR that doesn't break examples

Hi! Ok, I will check. Thank you for testing.

**Pull request closed without merging**
